### PR TITLE
V811 shajsyed

### PR DESCRIPTION
**Pull request by shajeena**

### CODE REVIEW

**Comment by shajeena** [comment]
@NatarajBTI - I have added the tablespace code in azure/deploy.sh

**Review by amitmangalvedkar — APPROVED** [review]
Approved

**Review by NatarajBTI — COMMENTED** [review]
Check whether DB Schema is applicable for databases other than DB2. Because the environment variable name is "MAS_APP_SETTINGS_DB2_SCHEMA" & I see only in DB2 we create schema explicitly using the command --> db2 create schema maximo authorization maximo. But in case of Oracle, we don't do it..Not sure about MS-SQL. I think you will know about it.

**Review by NatarajBTI — APPROVED** [review]
Other code changes look good apart from the above comment which needs to be checked on..Hence approving.

**Comment by shajeena** [comment]
> Check whether DB Schema is applicable for databases other than DB2. Because the environment variable name is "MAS_APP_SETTINGS_DB2_SCHEMA" & I see only in DB2 we create schema explicitly using the command --> db2 create schema maximo authorization maximo. But in case of Oracle, we don't do it..Not sure about MS-SQL. I think you will know about it.

@NatarajBTI - I will open a task for this ,will check with Manage team if they say schema not require . will remove the cancelling , for now will merge what say?

**Pull request merged**
