### PR TITLE
Corrections to CFT files (both dev & prod)

### PR DESCRIPTION
**Pull request by NatarajBTI**
Fixed many issues around in all 6 CFT files around cloning branches which was inconsistent (as it was cloning ocp410 branch in some cft files & mas89-alpha in others..In prod cft files, made it to point to -b clone 2.0.1 such that there will be consistency & when we go for production update for MAS 8.9, we can change it to 3.0 or 8.9), python version corrected to point to 3.9 from 3.8, & operationalmode missing in UPI CFT.

### CODE REVIEW

**Comment by padmankosalaram** [comment]
byol-upi\cft-mas-core.yaml is missing the below section, please correct it (the same section present in byol-upi\cft-mas-core-dev.yaml)

```
            - Label:
                default: Operational Mode
              Parameters:
                - OperationalMode
```

**Review by padmankosalaram — APPROVED** [review]
as discussed, approving.

**Comment by amitmangalvedkar** [comment]
The behaviour seems to be inconsistent - 
For e.g. check `byol-existing-ocp` , it has `cft-mas-core-dev.yaml` as
```
git clone https://github.com/ibm-mas/multicloud-bootstrap.git;
```

However, in the same folder for `cft-mas-core.yaml`, the repos and branch is
```
git clone -b 2.0.1 https://github.com/ibm-mas/multicloud-bootstrap.git;
```

This is in contrast with `byol-ipi`, which has for `cft-mas-core-dev.yaml` as 
```
git clone https://github.com/ibm-mas/multicloud-bootstrap.git;
```
and which again for `cft-mas-core.yaml` is
```
git clone -b 2.0.1 https://github.com/ibm-mas/multicloud-bootstrap.git;
```
Now if we check with `byol-upi` this is 
```
git clone -b mas89-alpha https://github.com/ibm-mas/multicloud-bootstrap.git
```
So for the same code drop we have 3 different branches for `ipi`, `upi` and `existing ocp`. All should point to a uniform branch.

**Comment by NatarajBTI** [comment]
Yes..that's because cft-mas-core.yaml is Production CFT file & cft-mas-core-dev.yaml is Dev CFT in case of all 3 folders (IPI, UPI, & Existing OCP)..

**Pull request merged**
