### PR TITLE
Mas89 alpha shajpy39

### PR DESCRIPTION
**Pull request by shajeena**
Python3.9 update in RHEL8 for azure

### CODE REVIEW

**Review by prasanthgelli1 — APPROVED** [review]
LGTM

**Comment by shajeena** [comment]
image

**Comment by shajeena** [comment]
started testing for MAS+core
Amrin will test for MAS+Manage

**Review by padmankosalaram — APPROVED** [review]

**Review by amitmangalvedkar — CHANGES_REQUESTED** [review]
Pl check the git repos, it is pointing to a different branch

**Comment by shajeena** [comment]
jdbc , validation done .

**Review by amitmangalvedkar — CHANGES_REQUESTED** [review]
If we are merging into `mas89-alpha` branch _(and not the `main` branch)_ then let the git pull also be in the `mas89-alpha` branch

**Review by amitmangalvedkar — APPROVED** [review]
This looks good, accepting the PR, pl merge

**Pull request merged**
