### PR TITLE
UPI CFT changes

### PR DESCRIPTION
**Pull request by shajeena**
CFT changes for UPI .
1. Removed the Existing OCP 
2. Bootnode to use the existingVPCId and existingpublicsubnet provided by the customer
3. Existing vpc and Subnets have lookup (a dropdown is displayed to choose the values)
4. Conditions for existing OCP removed
5. HostedZone - Public /private cluster added

### CODE REVIEW

**Comment by shajeena** [comment]
@amitmangalvedkar @santoshjpawar  -Can you please review these changes.

I ran the above CFT , It OCP cluster creation with existing VPC was created successfully, but failed at ansible playbook , checked 2 times failed with same error at SLS creation .

```
`2022-07-28 16:38:59 ==== SLS deployment started ====
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the
controller starting with Ansible 2.12. Current version: 3.6.8 (default, Jan 14
2022, 11:04:20) [GCC 8.5.0 20210514 (Red Hat 8.5.0-7)]. This feature will be
removed from ansible-core in version 2.12. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
[WARNING]: running playbook inside collection ibm.mas_devops

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [ibm.mas_devops.ansible_version_check : Verify minimum Ansible version is 2.10.3] ***
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [ibm.mas_devops.sls : include_tasks] **************************************
included: /root/.ansible/collections/ansible_collections/ibm/mas_devops/roles/sls/tasks/install/main.yml for localhost

TASK [ibm.mas_devops.sls : Fail if sls_entitlement_username has not been provided] ***
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [ibm.mas_devops.sls : Fail if sls_entitlement_key has not been provided] ***
fatal: [localhost]: FAILED! => {
    "assertion": "sls_entitlement_key is defined and sls_entitlement_key != \"\"",
    "changed": false,
    "evaluated_to": false,
    "msg": "sls_entitlement_key property has not been set"
}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

2022-07-28 16:39:01 Deployment return code is 2`

```

**Review by santoshjpawar — APPROVED** [review]
Looks good

**Comment by shajeena** [comment]
@santoshjpawar - Thanks - Deleted the cft-mas-core-dev-all.json

**Review by amitmangalvedkar — APPROVED** [review]
Approved!!!!

**Pull request merged**
