### PR TITLE
Gov cloud nov24

### PR DESCRIPTION
**Pull request by shajeena**

### CODE REVIEW

**Comment by shajeena** [comment]
@NatarajBTI @amitmangalvedkar - this is the final templates , Please check !!!!!

**Review by NatarajBTI — COMMENTED** [review]
Please remove PrivateCluster parameter from CFT files & even remove conditions where in it checks for existing MongoDB..Now we only support Existing Mongo instance itself so no need to check with a condition on that..

**Review by NatarajBTI — COMMENTED** [review]
In Existing OCP CFT file, add a note saying "Make sure your existing OCP cluster is FIPS enabled".. You can add this note in OpenShiftClusterApiUrl parameter's text description..

**Comment by shajeena** [comment]
> Please remove PrivateCluster parameter from CFT files & even remove conditions where in it checks for existing MongoDB..Now we only support Existing Mongo instance itself so no need to check with a condition on that..

Yes , PrivateCluster is removed , thanks it was missed in core.yaml . 
Thanks , Conditions were removed from the parameters to init.sh ,have removed from conditions sections aswell

**Pull request merged**
